### ISSUE TITLE
RuntimeError: Failed to call ninja

### ISSUE THREAD

**Issue by yuxiaoz** [AIS-Bonn/stillleben#4]
Cannot find build.ninja

-- Configuring incomplete, errors occurred!
See also "/home/z*******o/stillleben/python/cpp_build/CMakeFiles/CMakeOutput.log".
Failed to run "cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_INSTALL_PREFIX=/home/z*******o/stillleben/python/stillleben -DUSE_RELATIVE_RPATH=ON -GNinja ../.. -DEXTRA_RPATH=/home/z*******o/anaconda3/envs/test_stillleben/lib"
ninja: error: loading 'build.ninja': No such file or directory
Traceback (most recent call last):
  File "setup.py", line 115, in <module>
    'dist_dir': 'python/dist'
  File "/home/z*******o/anaconda3/envs/test_stillleben/lib/python3.7/site-packages/setuptools/__init__.py", line 163, in setup
    return distutils.core.setup(**attrs)
  File "/home/z*******o/anaconda3/envs/test_stillleben/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/z*******o/anaconda3/envs/test_stillleben/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/z*******o/anaconda3/envs/test_stillleben/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 82, in run
    self.run_command('build_deps')
  File "/home/z*******o/anaconda3/envs/test_stillleben/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/z*******o/anaconda3/envs/test_stillleben/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 77, in run
    build_stillleben()
  File "setup.py", line 52, in build_stillleben
    raise RuntimeError('Failed to call ninja')
RuntimeError: Failed to call ninja

How to add "build.ninja" ?

**Comment by yuxiaoz** [comment]
Since ninja is installed by conda, no build.ninja is found when compiling on Ubuntu16.04,

**Comment by xqms** [comment]
Hi! From your earlier ticket I assume you are trying to install stillleben on Ubuntu 16.04, which is not supported. It may work, but you are on your own...

Regarding assimp: There is an Ubuntu package called `libassimp-dev`, simply install that one using `apt`.

**Comment by xqms** [comment]
Closing this as there has been no further activity and 16.04 is even older now ;)
